#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Tasvirci by OsmanDE
# github.com/OsmanDE/Tasvirci

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GridSetupDialog(object):
    def setupUi(self, GridSetupDialog):
        GridSetupDialog.setObjectName("GridSetupDialog")
        GridSetupDialog.setWindowModality(QtCore.Qt.WindowModal)
        GridSetupDialog.resize(441, 240)
        self.gridLayout = QtWidgets.QGridLayout(GridSetupDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(GridSetupDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(GridSetupDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(GridSetupDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinPaperWidth = QtWidgets.QSpinBox(GridSetupDialog)
        self.spinPaperWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.spinPaperWidth.setMinimum(1)
        self.spinPaperWidth.setMaximum(500)
        self.spinPaperWidth.setProperty("value", 6)
        self.spinPaperWidth.setObjectName("spinPaperWidth")
        self.gridLayout.addWidget(self.spinPaperWidth, 0, 1, 1, 1)
        self.spinPhotoWidth = QtWidgets.QDoubleSpinBox(GridSetupDialog)
        self.spinPhotoWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.spinPhotoWidth.setDecimals(1)
        self.spinPhotoWidth.setMinimum(1.0)
        self.spinPhotoWidth.setSingleStep(0.1)
        self.spinPhotoWidth.setProperty("value", 3.5)
        self.spinPhotoWidth.setObjectName("spinPhotoWidth")
        self.gridLayout.addWidget(self.spinPhotoWidth, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(GridSetupDialog)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(GridSetupDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.spinPaperHeight = QtWidgets.QSpinBox(GridSetupDialog)
        self.spinPaperHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.spinPaperHeight.setMinimum(1)
        self.spinPaperHeight.setMaximum(500)
        self.spinPaperHeight.setProperty("value", 4)
        self.spinPaperHeight.setObjectName("spinPaperHeight")
        self.gridLayout.addWidget(self.spinPaperHeight, 0, 3, 1, 1)
        self.spinPhotoHeight = QtWidgets.QDoubleSpinBox(GridSetupDialog)
        self.spinPhotoHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.spinPhotoHeight.setDecimals(1)
        self.spinPhotoHeight.setMinimum(1.0)
        self.spinPhotoHeight.setSingleStep(0.1)
        self.spinPhotoHeight.setProperty("value", 4.5)
        self.spinPhotoHeight.setObjectName("spinPhotoHeight")
        self.gridLayout.addWidget(self.spinPhotoHeight, 2, 3, 1, 1)
        self.spinDPI = QtWidgets.QSpinBox(GridSetupDialog)
        self.spinDPI.setAlignment(QtCore.Qt.AlignCenter)
        self.spinDPI.setMinimum(100)
        self.spinDPI.setMaximum(1200)
        self.spinDPI.setProperty("value", 300)
        self.spinDPI.setObjectName("spinDPI")
        self.gridLayout.addWidget(self.spinDPI, 1, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(GridSetupDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.paperSizeUnit = QtWidgets.QComboBox(GridSetupDialog)
        self.paperSizeUnit.setObjectName("paperSizeUnit")
        self.paperSizeUnit.addItem("")
        self.paperSizeUnit.addItem("")
        self.paperSizeUnit.addItem("")
        self.gridLayout.addWidget(self.paperSizeUnit, 0, 4, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(GridSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 5)

        self.retranslateUi(GridSetupDialog)
        self.buttonBox.accepted.connect(GridSetupDialog.accept)
        self.buttonBox.rejected.connect(GridSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GridSetupDialog)

    def retranslateUi(self, GridSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        GridSetupDialog.setWindowTitle(_translate("GridSetupDialog", "Tasvirci - Grid Ayarları"))
        self.label.setText(_translate("GridSetupDialog", "Boyut: "))
        self.label_2.setText(_translate("GridSetupDialog", "DPI :"))
        self.label_3.setText(_translate("GridSetupDialog", "Fotoğraf Boyutu :"))
        self.label_5.setText(_translate("GridSetupDialog", "x"))
        self.label_6.setText(_translate("GridSetupDialog", "x"))
        self.label_4.setText(_translate("GridSetupDialog", "cm"))
        self.paperSizeUnit.setItemText(0, _translate("GridSetupDialog", "inch"))
        self.paperSizeUnit.setItemText(1, _translate("GridSetupDialog", "cm"))
        self.paperSizeUnit.setItemText(2, _translate("GridSetupDialog", "mm"))

